#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "magic-cdp-protocol-"));
const meta = await fetch("https://registry.npmjs.org/devtools-protocol/latest").then((r) => r.json());
const tgz = path.join(tmp, "devtools-protocol.tgz");
fs.writeFileSync(tgz, Buffer.from((await fetch(meta.dist.tarball).then((r) => r.arrayBuffer())) as ArrayBuffer));
execFileSync("tar", ["-xzf", tgz, "-C", tmp]);

const pkg = path.join(tmp, "package");
const domains = ["json/js_protocol.json", "json/browser_protocol.json"]
  .flatMap((file) => JSON.parse(fs.readFileSync(path.join(pkg, file), "utf8")).domains || [])
  .sort((a, b) => a.domain.localeCompare(b.domain));

const word = (x) => (/^[$A-Z_a-z][$\w]*$/.test(x) ? x : JSON.stringify(x));
const safe = (x) => x.replaceAll(/[^A-Z_a-z0-9]/g, "_").replace(/^(\d)/, "_$1");
const title = (x) => (x ? x[0].toUpperCase() + x.slice(1) : x);
const name = (d, x) => `${safe(d)}_${safe(x)}`;
const params = (x) => `${title(x)}Params`;
const result = (x) => `${title(x)}Result`;
const event = (x) => `${title(x)}Event`;

const zexpr = (x, d) => {
  if (!x) return "z.unknown()";
  if (x.$ref) {
    const [rd, rn] = x.$ref.includes(".") ? x.$ref.split(".", 2) : [d, x.$ref];
    return `z.lazy(() => ${name(rd, rn)})`;
  }
  if (x.enum) return x.enum.length ? `z.enum([${x.enum.map(JSON.stringify).join(", ")}])` : "z.string()";
  if (x.type === "array") return `z.array(${zexpr(x.items, d)})`;
  if (x.type === "object") return x.properties?.length ? zobj(x.properties, d) : "z.record(z.string(), z.unknown())";
  if (x.type === "integer") return "z.number().int()";
  if (x.type === "number") return "z.number()";
  if (x.type === "boolean") return "z.boolean()";
  if (x.type === "any") return "z.any()";
  return "z.string()";
};

const zobj = (xs: any[] = [], d: string) =>
  `z.object({ ${xs.map((x) => `${JSON.stringify(x.name)}: ${zexpr(x, d)}${x.optional ? ".optional()" : ""}`).join(", ")} }).passthrough()`;
const magicTypes = [
  ...fs.readFileSync(path.join(here, "magic.ts"), "utf8").matchAll(/^export type Magic([A-Z]\w*)\s*=/gm),
].map((match) => ({ name: match[1], type: `Magic${match[1]}` }));
const magicTypeNames = new Set(magicTypes.map((x) => x.name));
const magicCommands = magicTypes
  .filter((x) => x.name.endsWith("Params"))
  .map((x) => x.name.slice(0, -"Params".length))
  .filter((base) => magicTypeNames.has(`${base}Response`));
const method = (x) => (x ? x[0].toLowerCase() + x.slice(1) : x);
const hasRequiredParams = (x) => (x.parameters || []).some((p) => !p.optional);
const hasCommandsOrEvents = (d) => (d.commands || []).length || (d.events || []).length;

const emitCdpNamespace = (lines, indent = "") => {
  for (const d of domains) {
    lines.push(`${indent}export namespace ${d.domain} {`);
    for (const x of d.types || [])
      lines.push(`${indent}  export type ${x.id} = z.infer<typeof zod.${d.domain}.${word(x.id)}>;`);
    for (const x of d.commands || []) {
      lines.push(`${indent}  export type ${params(x.name)} = z.infer<typeof zod.${d.domain}.${word(params(x.name))}>;`);
      lines.push(`${indent}  export type ${result(x.name)} = z.infer<typeof zod.${d.domain}.${word(result(x.name))}>;`);
    }
    for (const x of d.events || [])
      lines.push(`${indent}  export type ${event(x.name)} = z.infer<typeof zod.${d.domain}.${word(event(x.name))}>;`);
    lines.push(`${indent}}`);
  }
};

const emitMagicNamespace = (lines, indent = "") => {
  lines.push(`${indent}export namespace Magic {`);
  for (const x of magicTypes) lines.push(`${indent}  export type ${x.name} = ${x.type};`);
  lines.push(`${indent}}`);
};

const cdp = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `import { zod, commands, events, types as runtimeTypes } from "./zod.js";`,
  `import type { z } from "zod";`,
  `import type { ${magicTypes.map((x) => x.type).join(", ")} } from "./magic.js";`,
  ``,
  `export const REQUEST = "request" as const;`,
  `export const RESPONSE = "response" as const;`,
  `export const EVENT = "event" as const;`,
  ``,
  `export { zod, commands, events };`,
  `export const cdp = { types: runtimeTypes, commands, events, REQUEST, RESPONSE, EVENT } as const;`,
  `export const types = cdp.types;`,
  ``,
  `export namespace cdp {`,
  `  export namespace types {`,
  `    export namespace ts {`,
];
emitMagicNamespace(cdp, "      ");
emitCdpNamespace(cdp, "      ");
cdp.push(`    }`, `  }`, `}`, ``);

const aliases = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `import type { z } from "zod";`,
  `import type { cdp } from "./cdp.js";`,
  `import { commands, events, types as runtimeTypes } from "./zod.js";`,
  `import { Magic, normalizeMagicName, normalizeMagicPayloadSchema } from "./magic.js";`,
  ``,
  `export type CdpNamedValue<Name extends string = string, Kind extends string = string> = { readonly id: Name; readonly name: Name; readonly kind: Kind; meta(): { id: Name; name: Name; kind: Kind } };`,
  `export type CdpCommandAlias<Params, Result, Name extends string> = ((params: Params) => Promise<Result>) & CdpNamedValue<Name, "command">;`,
  `export type CdpOptionalCommandAlias<Params, Result, Name extends string> = ((params?: Params) => Promise<Result>) & CdpNamedValue<Name, "command">;`,
  `export type CdpEventAlias<Payload, Name extends string> = z.ZodType<Payload> & CdpNamedValue<Name, "event">;`,
  `export type CdpAliasSend = (method: string, params?: unknown) => Promise<unknown>;`,
  `export type CdpAliasHooks = {`,
  `  onCustomCommand?: (name: string, paramsSchema?: z.ZodType | null, resultSchema?: z.ZodType | null) => void;`,
  `  onCustomEvent?: (name: string, eventSchema?: z.ZodType | null) => void;`,
  `};`,
  ``,
  `export type CdpAliases = {`,
  `  readonly types: typeof runtimeTypes;`,
  `  readonly commands: typeof commands;`,
  `  readonly events: typeof events;`,
  `  readonly REQUEST: "request";`,
  `  readonly RESPONSE: "response";`,
  `  readonly EVENT: "event";`,
];
for (const d of domains) {
  if (!hasCommandsOrEvents(d)) continue;
  aliases.push(`  ${word(d.domain)}: {`);
  for (const x of d.commands || []) {
    const optional = !hasRequiredParams(x);
    const commandName = `${d.domain}.${x.name}`;
    aliases.push(
      `    ${word(x.name)}: ${optional ? "CdpOptionalCommandAlias" : "CdpCommandAlias"}<cdp.types.ts.${d.domain}.${params(x.name)}, cdp.types.ts.${d.domain}.${result(x.name)}, ${JSON.stringify(commandName)}>;`,
    );
  }
  for (const x of d.events || []) {
    const eventName = `${d.domain}.${x.name}`;
    aliases.push(
      `    ${word(x.name)}: CdpEventAlias<cdp.types.ts.${d.domain}.${event(x.name)}, ${JSON.stringify(eventName)}>;`,
    );
  }
  aliases.push(`  };`);
}
aliases.push(`  Magic: {`);
for (const base of magicCommands) {
  const optional = base === "Ping";
  aliases.push(
    `    ${method(base)}(${optional ? "params?" : "params"}: cdp.types.ts.Magic.${base}Params): Promise<cdp.types.ts.Magic.${base}Response>;`,
  );
}
aliases.push(`  };`, `};`, ``);

aliases.push(
  `function withCdpName<T extends object, Name extends string, Kind extends string>(value: T, id: Name, kind: Kind): T & CdpNamedValue<Name, Kind> {`,
  `  Object.defineProperties(value, {`,
  `    id: { value: id, enumerable: true, configurable: true },`,
  `    name: { value: id, configurable: true },`,
  `    kind: { value: kind, enumerable: true, configurable: true },`,
  `  });`,
  `  if (!("meta" in value)) Object.defineProperty(value, "meta", { value: () => ({ id, name: id, kind }), configurable: true });`,
  `  return value as T & CdpNamedValue<Name, Kind>;`,
  `}`,
  ``,
  `export function createCdpAliases(send: CdpAliasSend, hooks: CdpAliasHooks = {}): CdpAliases {`,
  `  return {`,
  `    types: runtimeTypes,`,
  `    commands,`,
  `    events,`,
  `    REQUEST: "request",`,
  `    RESPONSE: "response",`,
  `    EVENT: "event",`,
);
for (const d of domains) {
  if (!hasCommandsOrEvents(d)) continue;
  aliases.push(`    ${word(d.domain)}: {`);
  for (const x of d.commands || []) {
    const commandName = `${d.domain}.${x.name}`;
    aliases.push(
      `      ${word(x.name)}: withCdpName(async (params?: unknown) => commands[${JSON.stringify(commandName)}].result.parse(await send(${JSON.stringify(commandName)}, commands[${JSON.stringify(commandName)}].params.parse(params ?? {}))), ${JSON.stringify(commandName)}, "command"),`,
    );
  }
  for (const x of d.events || []) {
    const eventName = `${d.domain}.${x.name}`;
    aliases.push(
      `      ${word(x.name)}: events[${JSON.stringify(eventName)}] as CdpEventAlias<cdp.types.ts.${d.domain}.${event(x.name)}, ${JSON.stringify(eventName)}>,`,
    );
  }
  aliases.push(`    },`);
}
aliases.push(`    Magic: {`);
for (const base of magicCommands) {
  const methodName = method(base);
  const commandName = `Magic.${methodName}`;
  const lines = [
    `      ${methodName}: async (params?: unknown) => {`,
    `        const parsed = Magic.${base}Params.parse(params ?? {});`,
  ];
  if (base === "AddCustomCommand") {
    lines.push(
      `        const name = normalizeMagicName(parsed.name);`,
      `        const paramsSchema = normalizeMagicPayloadSchema(parsed.paramsSchema);`,
      `        const resultSchema = normalizeMagicPayloadSchema(parsed.resultSchema);`,
      `        const response = Magic.${base}Response.parse(await send(${JSON.stringify(commandName)}, { ...parsed, name, paramsSchema: null, resultSchema: null }));`,
      `        hooks.onCustomCommand?.(name, paramsSchema, resultSchema);`,
      `        return response;`,
    );
  } else if (base === "AddCustomEvent") {
    lines.push(
      `        const directSchema = Magic.ZodType.safeParse(parsed);`,
      `        if (directSchema.success) {`,
      `          const name = normalizeMagicName(directSchema.data);`,
      `          const eventSchema = normalizeMagicPayloadSchema(directSchema.data);`,
      `          const response = Magic.${base}Response.parse(await send(${JSON.stringify(commandName)}, { name, eventSchema: null }));`,
      `          hooks.onCustomEvent?.(name, eventSchema);`,
      `          return response;`,
      `        }`,
      `        const objectParams = Magic.AddCustomEventObjectParams.parse(parsed);`,
      `        const name = normalizeMagicName(objectParams.name);`,
      `        const eventSchema = normalizeMagicPayloadSchema(objectParams.eventSchema);`,
      `        const response = Magic.${base}Response.parse(await send(${JSON.stringify(commandName)}, { ...objectParams, name, eventSchema: null }));`,
      `        hooks.onCustomEvent?.(name, eventSchema);`,
      `        return response;`,
    );
  } else if (base === "AddMiddleware") {
    lines.push(
      `        const name = parsed.name == null ? undefined : normalizeMagicName(parsed.name);`,
      `        return Magic.${base}Response.parse(await send(${JSON.stringify(commandName)}, { ...parsed, name }));`,
    );
  } else {
    lines.push(`        return Magic.${base}Response.parse(await send(${JSON.stringify(commandName)}, parsed));`);
  }
  lines.push(`      },`);
  aliases.push(...lines);
}
aliases.push(`    },`, `  };`, `}`, ``);

const zod = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `// @ts-nocheck -- recursive protocol schemas intentionally use lazy self/cross references.`,
  `import { z } from "zod";`,
  `import { Magic } from "./magic.js";`,
  ``,
  `const withCdpMeta = (schema, id, kind, extra = {}) => {`,
  `  const meta = { id, name: id, kind, ...extra };`,
  `  const named = schema.meta(meta);`,
  `  Object.defineProperties(named, {`,
  `    id: { value: id, enumerable: true, configurable: true },`,
  `    name: { value: id, configurable: true },`,
  `    kind: { value: kind, enumerable: true, configurable: true },`,
  `  });`,
  `  return named;`,
  `};`,
  ``,
];
for (const d of domains) {
  for (const x of d.types || [])
    zod.push(
      `const ${name(d.domain, x.id)} = withCdpMeta(${zexpr(x, d.domain)}, ${JSON.stringify(`${d.domain}.${x.id}`)}, "type");`,
    );
  for (const x of d.commands || []) {
    const commandName = `${d.domain}.${x.name}`;
    zod.push(
      `const ${name(d.domain, params(x.name))} = withCdpMeta(${zobj(x.parameters || [], d.domain)}, ${JSON.stringify(`${commandName}.params`)}, "commandParams", { method: ${JSON.stringify(commandName)} });`,
    );
    zod.push(
      `const ${name(d.domain, result(x.name))} = withCdpMeta(${zobj(x.returns || [], d.domain)}, ${JSON.stringify(`${commandName}.result`)}, "commandResult", { method: ${JSON.stringify(commandName)} });`,
    );
  }
  for (const x of d.events || [])
    zod.push(
      `const ${name(d.domain, event(x.name))} = withCdpMeta(${zobj(x.parameters || [], d.domain)}, ${JSON.stringify(`${d.domain}.${x.name}`)}, "event", { phase: "event" });`,
    );
}
zod.push(``, `export const zod = {`);
zod.push(`  Magic,`);
for (const d of domains) {
  zod.push(`  ${word(d.domain)}: {`);
  for (const x of d.types || []) zod.push(`    ${word(x.id)}: ${name(d.domain, x.id)},`);
  for (const x of d.commands || [])
    zod.push(
      `    ${word(params(x.name))}: ${name(d.domain, params(x.name))},`,
      `    ${word(result(x.name))}: ${name(d.domain, result(x.name))},`,
    );
  for (const x of d.events || []) zod.push(`    ${word(event(x.name))}: ${name(d.domain, event(x.name))},`);
  zod.push(`  },`);
}
zod.push(`} as const;`, `export const commands = {`);
for (const d of domains)
  for (const x of d.commands || [])
    zod.push(
      `  ${JSON.stringify(`${d.domain}.${x.name}`)}: { params: ${name(d.domain, params(x.name))}, result: ${name(d.domain, result(x.name))} },`,
    );
zod.push(`} as const;`, `export const events = {`);
for (const d of domains)
  for (const x of d.events || [])
    zod.push(`  ${JSON.stringify(`${d.domain}.${x.name}`)}: ${name(d.domain, event(x.name))},`);
zod.push(
  `} as const;`,
  `export const types = { zod } as const;`,
  `export const cdp = { types, commands, events } as const;`,
  ``,
);

fs.writeFileSync(path.join(here, "cdp.ts"), cdp.join("\n"));
fs.writeFileSync(path.join(here, "zod.ts"), zod.join("\n"));
fs.writeFileSync(path.join(here, "aliases.ts"), aliases.join("\n"));
fs.rmSync(tmp, { recursive: true, force: true });
console.log(
  `Generated types/cdp.ts, types/zod.ts, and types/aliases.ts from devtools-protocol@${meta.version} (${domains.length} domains).`,
);
