#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "magic-cdp-protocol-"));
const meta = await fetch("https://registry.npmjs.org/devtools-protocol/latest").then((r) => r.json());
const tgz = path.join(tmp, "devtools-protocol.tgz");
fs.writeFileSync(tgz, Buffer.from((await fetch(meta.dist.tarball).then((r) => r.arrayBuffer())) as ArrayBuffer));
execFileSync("tar", ["-xzf", tgz, "-C", tmp]);

const pkg = path.join(tmp, "package");
const domains = ["json/js_protocol.json", "json/browser_protocol.json"]
  .flatMap((file) => JSON.parse(fs.readFileSync(path.join(pkg, file), "utf8")).domains || [])
  .sort((a, b) => a.domain.localeCompare(b.domain));

const word = (x) => (/^[$A-Z_a-z][$\w]*$/.test(x) ? x : JSON.stringify(x));
const safe = (x) => x.replaceAll(/[^A-Z_a-z0-9]/g, "_").replace(/^(\d)/, "_$1");
const title = (x) => (x ? x[0].toUpperCase() + x.slice(1) : x);
const name = (d, x) => `${safe(d)}_${safe(x)}`;
const params = (x) => `${title(x)}Params`;
const result = (x) => `${title(x)}Result`;
const event = (x) => `${title(x)}Event`;

const zexpr = (x, d) => {
  if (!x) return "z.unknown()";
  if (x.$ref) {
    const [rd, rn] = x.$ref.includes(".") ? x.$ref.split(".", 2) : [d, x.$ref];
    return `z.lazy(() => ${name(rd, rn)})`;
  }
  if (x.enum) return x.enum.length ? `z.enum([${x.enum.map(JSON.stringify).join(", ")}])` : "z.string()";
  if (x.type === "array") return `z.array(${zexpr(x.items, d)})`;
  if (x.type === "object") return x.properties?.length ? zobj(x.properties, d) : "z.record(z.string(), z.unknown())";
  if (x.type === "integer") return "z.number().int()";
  if (x.type === "number") return "z.number()";
  if (x.type === "boolean") return "z.boolean()";
  if (x.type === "any") return "z.any()";
  return "z.string()";
};

const zobj = (xs: any[] = [], d: string) =>
  `z.object({ ${xs.map((x) => `${JSON.stringify(x.name)}: ${zexpr(x, d)}${x.optional ? ".optional()" : ""}`).join(", ")} }).passthrough()`;
const magicTypes = [
  ...fs.readFileSync(path.join(here, "magic.ts"), "utf8").matchAll(/^export type Magic([A-Z]\w*)\s*=/gm),
].map((match) => ({ name: match[1], type: `Magic${match[1]}` }));

const emitCdpNamespace = (lines, indent = "") => {
  for (const d of domains) {
    lines.push(`${indent}export namespace ${d.domain} {`);
    for (const x of d.types || [])
      lines.push(`${indent}  export type ${x.id} = z.infer<typeof zod.${d.domain}.${word(x.id)}>;`);
    for (const x of d.commands || []) {
      lines.push(`${indent}  export type ${params(x.name)} = z.infer<typeof zod.${d.domain}.${word(params(x.name))}>;`);
      lines.push(`${indent}  export type ${result(x.name)} = z.infer<typeof zod.${d.domain}.${word(result(x.name))}>;`);
    }
    for (const x of d.events || [])
      lines.push(`${indent}  export type ${event(x.name)} = z.infer<typeof zod.${d.domain}.${word(event(x.name))}>;`);
    lines.push(`${indent}}`);
  }
};

const emitMagicNamespace = (lines, indent = "") => {
  lines.push(`${indent}export namespace Magic {`);
  for (const x of magicTypes) lines.push(`${indent}  export type ${x.name} = ${x.type};`);
  lines.push(`${indent}}`);
};

const cdp = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `import { zod, commands, events, types as runtimeTypes } from "./zod.js";`,
  `import type { z } from "zod";`,
  `import type { ${magicTypes.map((x) => x.type).join(", ")} } from "./magic.js";`,
  ``,
  `export { zod, commands, events };`,
  `export const cdp = { types: runtimeTypes, commands, events } as const;`,
  `export const types = cdp.types;`,
  ``,
  `export namespace cdp {`,
  `  export namespace types {`,
  `    export namespace ts {`,
];
emitMagicNamespace(cdp, "      ");
emitCdpNamespace(cdp, "      ");
cdp.push(`    }`, `  }`, `}`, ``);

const zod = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `// @ts-nocheck -- recursive protocol schemas intentionally use lazy self/cross references.`,
  `import { z } from "zod";`,
  `import { Magic } from "./magic.js";`,
  ``,
];
for (const d of domains) {
  for (const x of d.types || []) zod.push(`const ${name(d.domain, x.id)} = ${zexpr(x, d.domain)};`);
  for (const x of d.commands || []) {
    zod.push(`const ${name(d.domain, params(x.name))} = ${zobj(x.parameters || [], d.domain)};`);
    zod.push(`const ${name(d.domain, result(x.name))} = ${zobj(x.returns || [], d.domain)};`);
  }
  for (const x of d.events || [])
    zod.push(`const ${name(d.domain, event(x.name))} = ${zobj(x.parameters || [], d.domain)};`);
}
zod.push(``, `export const zod = {`);
zod.push(`  Magic,`);
for (const d of domains) {
  zod.push(`  ${word(d.domain)}: {`);
  for (const x of d.types || []) zod.push(`    ${word(x.id)}: ${name(d.domain, x.id)},`);
  for (const x of d.commands || [])
    zod.push(
      `    ${word(params(x.name))}: ${name(d.domain, params(x.name))},`,
      `    ${word(result(x.name))}: ${name(d.domain, result(x.name))},`,
    );
  for (const x of d.events || []) zod.push(`    ${word(event(x.name))}: ${name(d.domain, event(x.name))},`);
  zod.push(`  },`);
}
zod.push(`} as const;`, `export const commands = {`);
for (const d of domains)
  for (const x of d.commands || [])
    zod.push(
      `  ${JSON.stringify(`${d.domain}.${x.name}`)}: { params: ${name(d.domain, params(x.name))}, result: ${name(d.domain, result(x.name))} },`,
    );
zod.push(`} as const;`, `export const events = {`);
for (const d of domains)
  for (const x of d.events || [])
    zod.push(`  ${JSON.stringify(`${d.domain}.${x.name}`)}: ${name(d.domain, event(x.name))},`);
zod.push(
  `} as const;`,
  `export const types = { zod } as const;`,
  `export const cdp = { types, commands, events } as const;`,
  ``,
);

fs.writeFileSync(path.join(here, "cdp.ts"), cdp.join("\n"));
fs.writeFileSync(path.join(here, "zod.ts"), zod.join("\n"));
fs.rmSync(tmp, { recursive: true, force: true });
console.log(
  `Generated types/cdp.ts and types/zod.ts from devtools-protocol@${meta.version} (${domains.length} domains).`,
);
