// Generated by types/codegen.ts from devtools-protocol@0.0.1621552. Do not edit by hand.
import { Mod } from "./modcdp.js";
import * as Accessibility from "./zod/Accessibility.js";
import * as Animation from "./zod/Animation.js";
import * as Audits from "./zod/Audits.js";
import * as Autofill from "./zod/Autofill.js";
import * as BackgroundService from "./zod/BackgroundService.js";
import * as BluetoothEmulation from "./zod/BluetoothEmulation.js";
import * as Browser from "./zod/Browser.js";
import * as CacheStorage from "./zod/CacheStorage.js";
import * as Cast from "./zod/Cast.js";
import * as Console from "./zod/Console.js";
import * as CrashReportContext from "./zod/CrashReportContext.js";
import * as CSS from "./zod/CSS.js";
import * as Debugger from "./zod/Debugger.js";
import * as DeviceAccess from "./zod/DeviceAccess.js";
import * as DeviceOrientation from "./zod/DeviceOrientation.js";
import * as DOM from "./zod/DOM.js";
import * as DOMDebugger from "./zod/DOMDebugger.js";
import * as DOMSnapshot from "./zod/DOMSnapshot.js";
import * as DOMStorage from "./zod/DOMStorage.js";
import * as Emulation from "./zod/Emulation.js";
import * as EventBreakpoints from "./zod/EventBreakpoints.js";
import * as Extensions from "./zod/Extensions.js";
import * as FedCm from "./zod/FedCm.js";
import * as Fetch from "./zod/Fetch.js";
import * as FileSystem from "./zod/FileSystem.js";
import * as HeadlessExperimental from "./zod/HeadlessExperimental.js";
import * as HeapProfiler from "./zod/HeapProfiler.js";
import * as IndexedDB from "./zod/IndexedDB.js";
import * as Input from "./zod/Input.js";
import * as Inspector from "./zod/Inspector.js";
import * as IO from "./zod/IO.js";
import * as LayerTree from "./zod/LayerTree.js";
import * as Log from "./zod/Log.js";
import * as Media from "./zod/Media.js";
import * as Memory from "./zod/Memory.js";
import * as Network from "./zod/Network.js";
import * as Overlay from "./zod/Overlay.js";
import * as Page from "./zod/Page.js";
import * as Performance from "./zod/Performance.js";
import * as PerformanceTimeline from "./zod/PerformanceTimeline.js";
import * as Preload from "./zod/Preload.js";
import * as Profiler from "./zod/Profiler.js";
import * as PWA from "./zod/PWA.js";
import * as Runtime from "./zod/Runtime.js";
import * as Schema from "./zod/Schema.js";
import * as Security from "./zod/Security.js";
import * as ServiceWorker from "./zod/ServiceWorker.js";
import * as SmartCardEmulation from "./zod/SmartCardEmulation.js";
import * as Storage from "./zod/Storage.js";
import * as SystemInfo from "./zod/SystemInfo.js";
import * as Target from "./zod/Target.js";
import * as Tethering from "./zod/Tethering.js";
import * as Tracing from "./zod/Tracing.js";
import * as WebAudio from "./zod/WebAudio.js";
import * as WebAuthn from "./zod/WebAuthn.js";
import * as WebMCP from "./zod/WebMCP.js";

export const zod = {
  Mod,
  Accessibility: Accessibility.zod,
  Animation: Animation.zod,
  Audits: Audits.zod,
  Autofill: Autofill.zod,
  BackgroundService: BackgroundService.zod,
  BluetoothEmulation: BluetoothEmulation.zod,
  Browser: Browser.zod,
  CacheStorage: CacheStorage.zod,
  Cast: Cast.zod,
  Console: Console.zod,
  CrashReportContext: CrashReportContext.zod,
  CSS: CSS.zod,
  Debugger: Debugger.zod,
  DeviceAccess: DeviceAccess.zod,
  DeviceOrientation: DeviceOrientation.zod,
  DOM: DOM.zod,
  DOMDebugger: DOMDebugger.zod,
  DOMSnapshot: DOMSnapshot.zod,
  DOMStorage: DOMStorage.zod,
  Emulation: Emulation.zod,
  EventBreakpoints: EventBreakpoints.zod,
  Extensions: Extensions.zod,
  FedCm: FedCm.zod,
  Fetch: Fetch.zod,
  FileSystem: FileSystem.zod,
  HeadlessExperimental: HeadlessExperimental.zod,
  HeapProfiler: HeapProfiler.zod,
  IndexedDB: IndexedDB.zod,
  Input: Input.zod,
  Inspector: Inspector.zod,
  IO: IO.zod,
  LayerTree: LayerTree.zod,
  Log: Log.zod,
  Media: Media.zod,
  Memory: Memory.zod,
  Network: Network.zod,
  Overlay: Overlay.zod,
  Page: Page.zod,
  Performance: Performance.zod,
  PerformanceTimeline: PerformanceTimeline.zod,
  Preload: Preload.zod,
  Profiler: Profiler.zod,
  PWA: PWA.zod,
  Runtime: Runtime.zod,
  Schema: Schema.zod,
  Security: Security.zod,
  ServiceWorker: ServiceWorker.zod,
  SmartCardEmulation: SmartCardEmulation.zod,
  Storage: Storage.zod,
  SystemInfo: SystemInfo.zod,
  Target: Target.zod,
  Tethering: Tethering.zod,
  Tracing: Tracing.zod,
  WebAudio: WebAudio.zod,
  WebAuthn: WebAuthn.zod,
  WebMCP: WebMCP.zod,
} as const;
export const commands = {
  ...Accessibility.commands,
  ...Animation.commands,
  ...Audits.commands,
  ...Autofill.commands,
  ...BackgroundService.commands,
  ...BluetoothEmulation.commands,
  ...Browser.commands,
  ...CacheStorage.commands,
  ...Cast.commands,
  ...Console.commands,
  ...CrashReportContext.commands,
  ...CSS.commands,
  ...Debugger.commands,
  ...DeviceAccess.commands,
  ...DeviceOrientation.commands,
  ...DOM.commands,
  ...DOMDebugger.commands,
  ...DOMSnapshot.commands,
  ...DOMStorage.commands,
  ...Emulation.commands,
  ...EventBreakpoints.commands,
  ...Extensions.commands,
  ...FedCm.commands,
  ...Fetch.commands,
  ...FileSystem.commands,
  ...HeadlessExperimental.commands,
  ...HeapProfiler.commands,
  ...IndexedDB.commands,
  ...Input.commands,
  ...Inspector.commands,
  ...IO.commands,
  ...LayerTree.commands,
  ...Log.commands,
  ...Media.commands,
  ...Memory.commands,
  ...Network.commands,
  ...Overlay.commands,
  ...Page.commands,
  ...Performance.commands,
  ...PerformanceTimeline.commands,
  ...Preload.commands,
  ...Profiler.commands,
  ...PWA.commands,
  ...Runtime.commands,
  ...Schema.commands,
  ...Security.commands,
  ...ServiceWorker.commands,
  ...SmartCardEmulation.commands,
  ...Storage.commands,
  ...SystemInfo.commands,
  ...Target.commands,
  ...Tethering.commands,
  ...Tracing.commands,
  ...WebAudio.commands,
  ...WebAuthn.commands,
  ...WebMCP.commands,
} as const;
export const events = {
  ...Accessibility.events,
  ...Animation.events,
  ...Audits.events,
  ...Autofill.events,
  ...BackgroundService.events,
  ...BluetoothEmulation.events,
  ...Browser.events,
  ...CacheStorage.events,
  ...Cast.events,
  ...Console.events,
  ...CrashReportContext.events,
  ...CSS.events,
  ...Debugger.events,
  ...DeviceAccess.events,
  ...DeviceOrientation.events,
  ...DOM.events,
  ...DOMDebugger.events,
  ...DOMSnapshot.events,
  ...DOMStorage.events,
  ...Emulation.events,
  ...EventBreakpoints.events,
  ...Extensions.events,
  ...FedCm.events,
  ...Fetch.events,
  ...FileSystem.events,
  ...HeadlessExperimental.events,
  ...HeapProfiler.events,
  ...IndexedDB.events,
  ...Input.events,
  ...Inspector.events,
  ...IO.events,
  ...LayerTree.events,
  ...Log.events,
  ...Media.events,
  ...Memory.events,
  ...Network.events,
  ...Overlay.events,
  ...Page.events,
  ...Performance.events,
  ...PerformanceTimeline.events,
  ...Preload.events,
  ...Profiler.events,
  ...PWA.events,
  ...Runtime.events,
  ...Schema.events,
  ...Security.events,
  ...ServiceWorker.events,
  ...SmartCardEmulation.events,
  ...Storage.events,
  ...SystemInfo.events,
  ...Target.events,
  ...Tethering.events,
  ...Tracing.events,
  ...WebAudio.events,
  ...WebAuthn.events,
  ...WebMCP.events,
} as const;
export const types = { zod } as const;
export const cdp = { types, commands, events } as const;
